name: film_uygulamasi
description: "Film uygulaması"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  cached_network_image: ^3.2.0
  firebase_remote_config: ^5.3.1 
  firebase_core: ^3.10.1
  logger: ^2.5.0
  intl: ^0.18.0
  google_fonts: 6.2.1
  dart_style: ^3.0.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  fl_chart: ^0.70.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_profile_pic.jpg
    - assets/images/simba.jpg
    - assets/images/spider_man.jpg
    - assets/images/miles_morales.jpg
    - assets/images/edward.jpg
    - assets/images/dora.jpg

    - assets/images/darth_vader.jpg

    - assets/images/alien.jpg
    - assets/images/11.jpg
    - assets/images/stitch.jpg
    - assets/images/godzilla.jpg
