// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMzDRrCInoRvDPQLwTyuNHHjWzjvTNLjU',
    appId: '1:903303192378:web:cf6f6fdb149306d8e1ba03',
    messagingSenderId: '903303192378',
    projectId: 'film-uygulamasi-d0c21',
    authDomain: 'film-uygulamasi-d0c21.firebaseapp.com',
    storageBucket: 'film-uygulamasi-d0c21.firebasestorage.app',
    measurementId: 'G-0H97BB604X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXzdz_FPIIvcSb5v9kilbSLV6qldJdJAQ',
    appId: '1:903303192378:android:cab57e4ace9ff6dee1ba03',
    messagingSenderId: '903303192378',
    projectId: 'film-uygulamasi-d0c21',
    storageBucket: 'film-uygulamasi-d0c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_REuF9Ma1HXe--UqZPCsuUeizXPitO_g',
    appId: '1:903303192378:ios:7b555b8e684662fee1ba03',
    messagingSenderId: '903303192378',
    projectId: 'film-uygulamasi-d0c21',
    storageBucket: 'film-uygulamasi-d0c21.firebasestorage.app',
    iosBundleId: 'com.example.filmUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_REuF9Ma1HXe--UqZPCsuUeizXPitO_g',
    appId: '1:903303192378:ios:7b555b8e684662fee1ba03',
    messagingSenderId: '903303192378',
    projectId: 'film-uygulamasi-d0c21',
    storageBucket: 'film-uygulamasi-d0c21.firebasestorage.app',
    iosBundleId: 'com.example.filmUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMzDRrCInoRvDPQLwTyuNHHjWzjvTNLjU',
    appId: '1:903303192378:web:32e8fd49b28b35fde1ba03',
    messagingSenderId: '903303192378',
    projectId: 'film-uygulamasi-d0c21',
    authDomain: 'film-uygulamasi-d0c21.firebaseapp.com',
    storageBucket: 'film-uygulamasi-d0c21.firebasestorage.app',
    measurementId: 'G-H8W9D76YGJ',
  );
}
